### ISSUE TITLE
Match.Optional seems to be null on Bronze Matches.

### ISSUE THREAD

**Issue by stefanocorona83** [jacobhood/Challonge-DotNet#17]
![bronze_match_result](https://user-images.githubusercontent.com/64501232/216783022-8b04f4dd-0291-4e7c-ba24-ecac731dc78c.png)

I think the Optional property on Match object should be nullable.

**Comment by jacobhood** [comment]
Hey, thanks for the report. Should be fixed in ea196d9b2e0714d73a1fac89afa902b36b1067c7. NuGet package version 3.0.0 has been uploaded and appears to be available for download now.
