### ISSUE TITLE
Error on default swiss events

### ISSUE THREAD

**Issue by david-shattuck** [jacobhood/Challonge-DotNet#18]
Creating a swiss tournament with default values and then later starting the event will throw the below error. I think the problem is due to a spelling mistake in Challonge.Objects.Enum.cs.

The value for TieBreak.MedianBucholz is "median bucholz" - but Buchholz has two h's in it (https://en.wikipedia.org/wiki/Buchholz_system), so the value coming back from Challonge can't match an enum.

![Screenshot 2024-06-10 212205](https://github.com/jacobhood/Challonge-DotNet/assets/21180162/520846f8-e33b-41c7-a9bd-f0f5aaa84d71)

**Comment by jacobhood** [comment]
Hey David, thanks for raising this issue and providing a fix. I'll make the suggested change and add a test within the next few days.

**Comment by david-shattuck** [comment]
Thanks for a great API wrapper, I use it heavily (https://afifthofgaming.com/). My users are requesting Swiss events so here we are!

**Comment by jacobhood** [comment]
Thanks for the PR and apologies for not getting to it myself! The fixed version (3.0.1) has been uploaded to NuGet and should be available soon. Glad it's been mostly useful for you otherwise.
