### ISSUE TITLE
missing 'ranked' value throwing exceptions

### ISSUE THREAD

**Issue by david-shattuck** [jacobhood/Challonge-DotNet#20]
My "create a tournament" code suddenly started failing (I think it has been a 100% failure rate) a few days ago. At first glance it seems like the problem is challonge-dotnet is expecting the response from challonge to contain a value for 'Ranked' but it doesn't.

I don't know what 'Ranked' is or what it's used for, so I'm afraid to just say "oh just make it nullable" - but Ranked isn't listed in the challonge api sample response (https://api.challonge.com/v1/documents/tournaments/create). Maybe they quietly removed it? If so, did they quietly remove other stuff?

This same problem is causing my "get all pending tournaments" code to fail as well.

![Screenshot 2024-07-11 123923](https://github.com/jacobhood/Challonge-DotNet/assets/21180162/a4f5b31e-1ae7-4646-82ab-b8837aa5935d)

**Comment by jacobhood** [comment]
Hey David, thanks for your ongoing engagement with this project. I'm out of town at the moment but when I return early next week I'll review, presumably merge, publish the new package to Nuget, etc.

**Comment by david-shattuck** [comment]
Hi Jacob - Any news on this? Very sorry to pester but I'm doing a lot of manual updating while this persists (which also means delays for my users), so I'm eager to get it sorted. Happy to help if there's anything else I can do, just let me know.

**Comment by jacobhood** [comment]
Hey David, apologies once again for delays, I just merged your changes (thanks for taking care of that) and uploaded version 3.0.2 to NuGet, it should be available shortly.
